---
- name: 'Install perl dependencies'
  apt: name={{ item }} state=installed
  with_items:
      - libapache2-mod-perl2
      - libdbd-mysql-perl
      - libtimedate-perl
      - libnet-dns-perl
      - libnet-ldap-perl
      - libio-socket-ssl-perl
      - libpdf-api2-perl
      - libdbd-mysql-perl
      - libsoap-lite-perl
      - libtext-csv-xs-perl
      - libjson-xs-perl
      - libapache-dbi-perl
      - libxml-libxml-perl
      - libxml-libxslt-perl
      - libyaml-perl
      - libarchive-zip-perl
      - libcrypt-eksblowfish-perl
      - libencode-hanextra-perl
      - libmail-imapclient-perl
      - libtemplate-perl
      - libcrypt-ssleay-perl
      - libdbd-odbc-perl
      - libdbd-pg-perl
  become: true

- name: 'Check Perl modules'
  command: perl /opt/otrs/bin/otrs.CheckModules.pl
  become: true
  register: perl

- debug: var=perl.stdout_lines
